dist: trusty
sudo: required
language: c
compiler:
  - clang
  - gcc
env:
  - VER=4.1.10
  - VER=6.0.1
addons:
  apt:
    packages:
      - python-docutils
      - python-sphinx
before_install:
  - git submodule update --init --recursive
  - git clone -b varnish-$VER https://github.com/varnishcache/varnish-cache.git
  - cd varnish-cache && ./autogen.sh && ./configure && make &&
    sudo make install && sudo ldconfig && cd ..
  - ./autogen.sh
script:
  - ./configure && make CFLAGS="-Wall -Wextra -Werror" VERBOSE=1 distcheck
