language: c
compiler:
  - clang
  - gcc
env:
  - VER=4.0
  - VER=4.1
before_install:
  - git submodule update --init --recursive
  - sudo apt-get update
  - sudo apt-get install apt-transport-https python-docutils
  - curl -s https://repo.varnish-cache.org/ubuntu/GPG-key.txt |
    sudo apt-key add -
  - echo "deb https://repo.varnish-cache.org/ubuntu/ precise varnish-$VER" |
    sudo tee /etc/apt/sources.list.d/varnish-cache.list
  - sudo apt-get update
  - sudo apt-get install varnish libvarnishapi-dev
  - ./autogen.sh
script:
  - ./configure && make CFLAGS="-Wall -Wextra -Werror" &&
    make check VERBOSE=1
cache: apt
notifications:
  webhooks:
    urls:
      secure: "V0WKdDUdbqCMzFoJp9nrqgAPNW33YyeOra1SJAaW+EcGDiSjItWkowDjtnRNN6+Ph/ok/Dk2eFrLiNx54smVF+Ub35wHCftvb5Dg2NaSUEPOYhYo/sC1sEsAmrRR4IkenUTqsjoWT2uapVhy4sfIStUufRBLOMqMJOFITtpTbUQ="
    on_success: change
    on_failure: always
    on_start: never
