dist: trusty
sudo: required
language: c
compiler:
  - clang
  - gcc
env:
  - VER=4.0
  - VER=4.1
  - VER=5.0
before_install:
  - git submodule update --init --recursive
  - sudo apt-get update
  - sudo apt-get install python-docutils
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 82B186B4
  - echo
    "deb http://ppa.launchpad.net/fgsch/varnish-$VER/ubuntu trusty main" |
    sudo tee /etc/apt/sources.list.d/varnish-cache.list
  - sudo apt-get update
  - sudo apt-get install varnish libvarnishapi-dev
  - ./autogen.sh
script:
  - ./configure && make CFLAGS="-Wall -Wextra -Werror" VERBOSE=1 distcheck
cache: apt
notifications:
  webhooks:
    urls:
      secure: "Iu7ubvN/0qGSyU5f8XsGcY8Xn5uSuZZNQZZw4G5XqeXL6s7Uf1KMGRI2UtViFSV5+II2Wu5KFVox4pH0Jp5nVLo0YP5WpI+C9AaWwNVKt8DcGhzhDrXajXF5vyrKbFdoEwGJpe0ghBUjRHB16HjVniDYiJEDnHZwwtVqRMTVvAI="
