dist: trusty
sudo: required
language: c
compiler:
  - clang
  - gcc
env:
  - VER=40
  - VER=41
before_install:
  - git submodule update --init --recursive
  - sudo apt-get update
  - sudo apt-get install apt-transport-https python-docutils
  - curl -L https://packagecloud.io/fgsch/varnish-$VER/gpgkey |
    sudo apt-key add -
  - echo
    "deb https://packagecloud.io/fgsch/varnish-$VER/ubuntu/ trusty main" |
    sudo tee /etc/apt/sources.list.d/varnish-cache.list
  - sudo apt-get update
  - sudo apt-get install varnish libvarnishapi-dev
  - ./autogen.sh
script:
  - ./configure && make CFLAGS="-Wall -Wextra -Werror" VERBOSE=1 distcheck
cache: apt
notifications:
  webhooks:
    urls:
      - $GITTER_IM_URL
