dist: trusty
language: c
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - python-docutils
before_install:
  - git submodule update --init --recursive
  - git clone https://github.com/varnishcache/varnish-cache.git
  - cd varnish-cache && ./autogen.sh && ./configure && make && cd ..
  - env PKG_CONFIG_PATH=$(pwd)/varnish-cache ./autogen.sh
script:
  - ./configure && make CFLAGS="-Wall -Wextra -Werror" VERBOSE=1 distcheck
